# Generated by Django 5.0.2 on 2025-08-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="modification_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
