# Generated by Django 5.0.2 on 2025-08-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_note_creation_date_note_modification_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="modification_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
